//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comprension_Lectora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_CLINICO
    {
        public int CodigoHistorial { get; set; }
        public Nullable<int> Paciente { get; set; }
        public string Examentes_Realizados { get; set; }
        public string DiagnosticoPasiente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual PACIENTE PACIENTE1 { get; set; }
    }
}
