//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comprension_Lectora.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.HISTORIAL_CLINICO = new HashSet<HISTORIAL_CLINICO>();
        }
    
        public int CodigoPasiente { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<int> Sexo { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Enfermedad { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Habitacion { get; set; }
    
        public virtual ENFERMEDAD ENFERMEDAD1 { get; set; }
        public virtual HABITACION HABITACION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_CLINICO> HISTORIAL_CLINICO { get; set; }
        public virtual SEXO SEXO1 { get; set; }
    }
}
