//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comprension_Lectora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Passwords { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual CSTATE CSTATE { get; set; }
        public virtual PERSONAL_ADMISTRATIVO PERSONAL_ADMISTRATIVO { get; set; }
    }
}
